# Grafana service
apiVersion: v1
kind: Service
metadata:
  name: grafana-dev-service
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3000