# argoCD configuration file responsible for the netflix-nginx application deployment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-nginx
  namespace: argocd
  finalizers:
   # Delete application related resources when issuing application delete
   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/barrotem/NetflixInfra
    targetRevision: HEAD
    path: k8s/prod/NetflixNginx
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false