# netflix-mc k8s yaml for deployment
# 1. netflix-mc k8s yaml for deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-mc-prod-deployment
  labels:
    app: netflix-mc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-mc
  template:
    metadata:
      labels:
        app: netflix-mc
    spec:
      containers:
        - name: netflix-movie-catalog
          image: barrotem/netflix-mc:v1.0.6
