# netflix-mc k8s yaml for service
# 2. netflix-mc k8s yaml for service
apiVersion: v1
kind: Service
metadata:
  name: netflix-mc-prod-service
  labels:
    app: netflix-mc
spec:
  selector:
    app: netflix-mc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080