# netflix-mc k8s yaml for deployment
# 1. netflix-mc k8s yaml for deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-mc-deployment
  labels:
    app: netflix-mc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-mc
  template:
    metadata:
      labels:
        app: netflix-mc
    spec:
      containers:
        - name: netflix-movie-catalog
          image: barrotem/netflix-mc:3.0.20
          # Apply liveness and readiness probes on port 8080
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/"
              port: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/status"
              port: 8080
