# k8s config-map for nginx configuration files
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-prod-conf
data:
  default.conf: |
    server {
     listen 80;
     server_name  localhost;
     location / {
       proxy_pass http://netflix-frontend-prod-service:3000;
      }
    }