# netflixfe-canary k8s yaml for deployment
# 1. netflixfe-canary k8s yaml for deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflixfe-canary-deployment
  labels:
    app: netflixfe-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflixfe-canary
  template:
    metadata:
      labels:
        app: netflixfe-canary
    spec:
      containers:
        - name: netflix-frontend-canary
          image: barrotem/netflixfe:github-wf-deploy-20
          env:
            - name: MOVIE_CATALOG_SERVICE
              value: "http://netflix-mc-service:8080"
